-   id: flutter-analyze
    name: Flutter Code Analyze
    entry: run
    language: script
    files: \.dart$
    
-   id: flutter-format
    name: Flutter Code Format
    entry: run
    language: script
    files: \.dart$
